import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "tertiary-fixed": "#e9e1dd",
        "primary-container": "#801323",
        "on-tertiary-fixed": "#1e1b19",
        "outline": "#8b7171",
        "error-container": "#ffdad6",
        "surface-tint": "#aa333e",
        "surface-container-high": "#ebe8e3",
        "secondary-fixed": "#ffdcc2",
        "on-tertiary-fixed-variant": "#4b4643",
        "outline-variant": "#debfbf",
        "secondary": "#8f4e00",
        "surface": "#fcf9f4",
        "on-background": "#1c1c19",
        "on-primary-fixed": "#40000a",
        "tertiary": "#2d2927",
        "surface-bright": "#fcf9f4",
        "on-primary-fixed-variant": "#891b29",
        "surface-container-highest": "#e5e2dd",
        "on-primary-container": "#ff8a8e",
        "on-secondary-fixed": "#2e1500",
        "tertiary-container": "#443f3d",
        "on-secondary-container": "#6d3a00",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ffb3b3",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-surface": "#1c1c19",
        "on-surface-variant": "#574141",
        "on-secondary-fixed-variant": "#6d3a00",
        "surface-variant": "#e5e2dd",
        "inverse-primary": "#ffb3b3",
        "primary": "#5d0012",
        "surface-container": "#f0ede9",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fea047",
        "inverse-on-surface": "#f3f0eb",
        "surface-dim": "#dcdad5",
        "surface-container-low": "#f6f3ee",
        "tertiary-fixed-dim": "#cdc5c2",
        "on-tertiary-container": "#b2aaa7",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#ffdad9",
        "secondary-fixed-dim": "#ffb77a",
        "inverse-surface": "#31302d",
        "background": "#fcf9f4"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1.25rem",
        "space-sm": "0.5rem",
        "margin": "3rem",
        "gutter": "1.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "gutter-sm": "1rem"
      },
      fontFamily: {
        "title-md": ["var(--font-plus-jakarta)"],
        "price-tag": ["var(--font-plus-jakarta)"],
        "label-md": ["var(--font-plus-jakarta)"],
        "headline-lg-mobile": ["var(--font-newsreader)"],
        "body-md": ["var(--font-plus-jakarta)"],
        "headline-sm": ["var(--font-newsreader)"],
        "headline-md": ["var(--font-newsreader)"],
        "label-lg": ["var(--font-plus-jakarta)"],
        "body-lg": ["var(--font-plus-jakarta)"],
        "display-mobile": ["var(--font-newsreader)"],
        "title-lg": ["var(--font-plus-jakarta)"],
        "headline-lg": ["var(--font-newsreader)"],
        "display": ["var(--font-newsreader)"],
        "body-sm": ["var(--font-plus-jakarta)"]
      },
      fontSize: {
        "title-md": ["17px", { "lineHeight": "24px", "fontWeight": "600" }],
        "price-tag": ["16px", { "lineHeight": "20px", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "500" }],
        "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["22px", { "lineHeight": "30px", "fontWeight": "600" }],
        "headline-md": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-mobile": ["38px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.015em", "fontWeight": "500" }],
        "display": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
};
export default config;
